version: '3'
services:
  redis:
    image: redis:latest
    environment:
      - TZ=Asia/Shanghai
    command: redis-server --requirepass zP6gXX3y
    restart: always
  mysql:
    image: mysql:5.7.34
    environment:
      - MYSQL_ROOT_PASSWORD=zP6gXX3y
      - MYSQL_DATABASE=iast
      - TZ=Asia/Shanghai
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/
    restart: always
  backend:
    image: openjdk:11
    container_name: iast-server
    environment:
      - TZ=Asia/Shanghai
    command: java -jar /app/app.jar
    volumes:
      - ./backend/:/app/
    depends_on:
      - mysql
      - redis
    ports: 
      - "81:8989"
    restart: always
  frontend:
    image: nginx:latest
    container_name: iast-view
    volumes:
      - ./frontend/web/dist:/usr/share/nginx/html
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/:/var/log/nginx/
    command: nginx -g "daemon off;"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8443:80"
    depends_on:
      - backend

